### ISSUE TITLE
Does not work in Rails 4.0

### ISSUE THREAD

**Issue by hunterae** [khiav223577/left_joins#4]
Hello, I was attempting to use your gem and it does not appear to work in Rails 4, seemingly due to the fact the Rails 4.0 does not define JoinDependency#make_constraints (https://apidock.com/rails/ActiveRecord/Associations/JoinDependency/make_constraints). It appears to be introduced in Rails 4.1. I'm seeing if there's an easy way to fix.

**Comment by hunterae** [comment]
It does however appear that if you change the logic for your class ::ActiveRecord::Associations::JoinDependency changes so that the code goes through the Rails 3 condition code, it works. I'm not sure if the other Rails 3 checks also would need to be true for Rails 4 as I don't know my way through your code yet.

**Comment by hunterae** [comment]
Though it would seem my above suggestion breaks other stuff in ActiveRecord.

**Comment by khiav223577** [comment]
Thanks for your report. I will take a look at it.
I had a hard time making it to support Rails 3 because of the huge difference between Rails 3.2 and 4.2. Hope that supporting 4.0 is easier.

**Comment by khiav223577** [comment]
I managed to do it! Just release 1.0.3. You could try it out.

**Comment by hunterae** [comment]
Thanks for doing this. I'll try and test this out today to see if it works in our application. Much appreciated!
